ARG BASE_TAG=2019-latest
FROM mcr.microsoft.com/mssql/server:${BASE_TAG}

USER root
ENV DEBIAN_FRONTEND=noninteractive \
    MSSQL_DB_NAME=db \
    PATH="$PATH:/opt/mssql-tools/bin"

# Install ODBC Driver 17 for SQL Server and nftables to restrict access until database is ready
RUN apt-get update \
    && apt-get install -yqq gnupg2 curl iptables \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -yqq msodbcsql17 \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/

# Add latest mssql-tools
ADD https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/mssql-tools/mssql-tools_17.8.1.1-1_amd64.deb /root/
RUN dpkg --extract /root/mssql-tools_17.8.1.1-1_amd64.deb / \
    && rm /root/mssql-tools_17.8.1.1-1_amd64.deb

HEALTHCHECK --timeout=5s --retries=5 \
    CMD /bin/bash -c "test -f /var/opt/mssql/sql-server-up.marker"

COPY ./resources/startup.sh /startup.sh
RUN chmod +x /startup.sh

# Run container with necessary capabilities
CMD ["/startup.sh"]

# CMD ["bash", "-c", "exec /startup.sh --cap-add=NET_ADMIN"]
